version: '3'

services:
  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "15432:5432"
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USERNAME: datalake
      ADMINER_DEFAULT_PASSWORD: datalake
    ports:
      - 8081:8080
    

volumes:
  postgres_data:
